### ISSUE TITLE
HW5 review

### ISSUE THREAD

**Issue by sttung** [ntwieneke/DAT_SF_16#5]
I liked the approach for imputing values for the '?' values of bare_nuclei (since I just ended up dropping them) - how'd you decide on 0 instead of using the bare_nuclei average? 

Helpful to see how you built out the dummy variable for the Class feature - I ended up just using booleans, but might do this in the future instead if I want 0, 1 values.

@ghego @breucopter

**Comment by ghego** [comment]
Hey @ntwieneke seems your HW is incomplete. Do you have any questions? We'll go through the solution today.

**Comment by ntwieneke** [comment]
Hi Francesco,

Thank you for checking in, my HW 5 is incomplete but I wanted to focus on
getting the midterm completed first.  I did have a few questions for
homework 5 but going through the solutions today should answer them, thanks!


Nathan Wieneke
Support Representative | Backblaze Online Backup
B.A. Economics | University of California, San Diego
nathanwieneke@gmail.com
(650)-450-0152

**Comment by ghego** [comment]
ok
